// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalGameRouteDao is internal type for wrapping internal DAO implements.
type internalGameRouteDao = *internal.GameRouteDao

// gameRouteDao is the data access object for table hg_game_route.
// You can define custom methods on it to extend its functionality as you wish.
type gameRouteDao struct {
	internalGameRouteDao
}

var (
	// GameRoute is globally public accessible object for table hg_game_route operations.
	GameRoute = gameRouteDao{
		internal.NewGameRouteDao(),
	}
)

// Fill with you ideas below.
